language: go

go:
  - 1.6
  - tip
  - 1.3
  - 1.4
  
env:
  - TEST_EXTERNAL=1
  - TEST_EXTERNAL=0      

matrix:
  allow_failures:
    - go: 1.3
    - go: 1.4
    - go: tip
    - env: TEST_EXTERNAL=1
  fast_finish: true  

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:
 - go get -v -t .

script:
 - $HOME/gopath/bin/goveralls -service=travis-ci -v
