version: "{build}"

platform: x64

branches:
  only:
    - master

skip_tags: true

environment:
  GOVERSION: 1.7.4
  TEST_EXTERNAL: 1

install:
  - go version
  - go get -v -t .

build_script:
  - go test -v .
