version: '3'

services:
  stun-client:
    depends_on:
      - stun-server
    links:
      - stun-server
    build:
      context: ..
      dockerfile: e2e/Dockerfile
      args:
        CI_GO_VERSION: ${CI_GO_VERSION}
  stun-server:
    image: bprodoehl/turnserver
    environment:
      - SKIP_AUTO_IP=1
