resources:
- name: master
  type: git
  source:
    uri: git@github.com:cydev/stun.git
    branch: master
    private_key: {{stun-repo-key}}

- name: dev
  type: git
  source:
    uri: git@github.com:cydev/stun.git
    branch: dev
    private_key: {{stun-repo-key}}

jobs:
- name: build
  plan:
  - get: dev
    trigger: true
  - task: build
    file: cydev-stun/ci/build.yml

- name: test
  plan:
  - get: dev
    trigger: true
  - task: test
    file: cydev-stun/ci/test.yml

- name: lint
  plan:
  - get: dev
    trigger: true
  - task: lint
    file: cydev-stun/ci/lint.yml

- name: integration
  plan:
   - aggregate:
     - get: dev
       passed: [lint, test, build]
   - put: master
