resources:
- name: cydev-stun
  type: git
  source:
    uri: https://github.com/cydev/stun
    branch: master

jobs:
- name: build
  plan:
  - get: cydev-stun
    trigger: true
  - task: build
    file: cydev-stun/ci/build.yml
- name: test
  plan:
  - get: cydev-stun
    trigger: true
  - task: test
    file: cydev-stun/ci/test.yml
- name: lint
  plan:
  - get: cydev-stun
    trigger: true
  - task: lint
    file: cydev-stun/ci/lint.yml
