resources:
- name: cydev-stun
  type: git
  source:
    uri: https://github.com/cydev/stun
    branch: master

jobs:
- name: stun
  plan:
  - get: cydev-stun
    trigger: true
  - task: tests
    file: cydev-stun/ci/build.yml
